version: "3.2"
services:
  php-roki:
    build: './php/'
    networks:
      - backend
    volumes:
      - ../app:/var/www/html/
  apache-roki:
    build: './apache/'
    depends_on:
      - php-roki
      - db-roki
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ../app:/var/www/html/
  db-roki:
    image: mysql:5.7
    networks:
      - backend
    volumes:
      - ./data:/var/lib/mysql/
      - ./dump.sql.gz:/tmp/dump.sql.gz
      - ./init_dump.sh:/tmp/init_dump.sh
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=roki
      - MYSQL_DATABASE=roki
      - MYSQL_PASSWORD=roki
networks:
  frontend:
  backend:
